version: '3'
services:
  db:
    image: postgres
    env_file:
      - .env
  server:
    build: ./server
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rake db:create && bundle exec rake db:migrate && bundle exec rake db:seed && rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - .env
    links:
      - db
      - client
    volumes:
      - ./:/app
    depends_on:
      - db
      - client
    ports:
      - '3000:3000'
  client:
    build: ./client
    env_file:
      - .env
    command: ["npm", "start"]
    ports:
      - "3001:3001"
    volumes:
      - ./client:/app
