version: '3'
services:
 db:
    image: postgres:9.6.1-alpine
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=app_development
  backend:
    build: ./backend
    command: rails s --binding=0.0.0.0
    entrypoint: ./scripts/backend_entrypoint.sh
    links:
      - db
      - frontend
    volumes:
      - ./:/app
    depends_on:
      - db
      - frontend
  frontend:
    build: ./frontend
    command: npm start
    entrypoint: ./scripts/frontend_entrypoint.sh
    volumes:
      - ./client:/app
    environment:
      NODE_ENV: development
